[2024-05-28T19:13:15.786+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork3_dag.task4 scheduled__2024-05-28T19:11:50+00:00 [queued]>
[2024-05-28T19:13:16.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork3_dag.task4 scheduled__2024-05-28T19:11:50+00:00 [queued]>
[2024-05-28T19:13:16.052+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T19:13:16.535+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task4> on 2024-05-28 19:11:50+00:00
[2024-05-28T19:13:16.693+0000] {standard_task_runner.py:60} INFO - Started process 5040 to run task
[2024-05-28T19:13:16.799+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork3_dag', 'task4', 'scheduled__2024-05-28T19:11:50+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/fork_3.py', '--cfg-path', '/tmp/tmprprswjcc']
[2024-05-28T19:13:16.802+0000] {standard_task_runner.py:88} INFO - Job 281: Subtask task4
[2024-05-28T19:13:17.030+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:13:17.543+0000] {task_command.py:423} INFO - Running <TaskInstance: fork3_dag.task4 scheduled__2024-05-28T19:11:50+00:00 [running]> on host ac6c883b25f7
[2024-05-28T19:13:18.208+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork3_dag' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T19:11:50+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T19:11:50+00:00'
[2024-05-28T19:13:18.232+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T19:13:18.248+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T19:13:18.312+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork3_dag, task_id=task4, execution_date=20240528T191150, start_date=20240528T191315, end_date=20240528T191318
[2024-05-28T19:13:18.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T19:13:18.550+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
