[2024-06-06T17:58:30.840+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table.create_table manual__2024-06-06T17:58:21.585470+00:00 [queued]>
[2024-06-06T17:58:30.890+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table.create_table manual__2024-06-06T17:58:21.585470+00:00 [queued]>
[2024-06-06T17:58:30.891+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-06-06T17:58:30.959+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-06 17:58:21.585470+00:00
[2024-06-06T17:58:30.979+0000] {standard_task_runner.py:60} INFO - Started process 1818 to run task
[2024-06-06T17:58:30.983+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table', 'create_table', 'manual__2024-06-06T17:58:21.585470+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmpkx0lpp84']
[2024-06-06T17:58:30.998+0000] {standard_task_runner.py:88} INFO - Job 313: Subtask create_table
[2024-06-06T17:58:31.055+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-06T17:58:31.168+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table.create_table manual__2024-06-06T17:58:21.585470+00:00 [running]> on host 74448e5e1f02
[2024-06-06T17:58:31.401+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T17:58:21.585470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T17:58:21.585470+00:00'
[2024-06-06T17:58:31.404+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS customer (
            id UUID PRIMARY KEY,
            lastname VARCHAR NOT NULL,
            firstname VARCHAR NOT NULL,
            sex VARCHAR NOT NULL,
            street_number SMALLINT NOT NULL,
            street_name VARCHAR NOT NULL,
            city VARCHAR NOT NULL,
            postcode VARCHAR NOT NULL,
            region VARCHAR NOT NULL,
            modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
       
[2024-06-06T17:58:31.443+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-06-06T17:58:31.473+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-06-06T17:58:31.485+0000] {sql.py:450} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS customer (
            id UUID PRIMARY KEY,
            lastname VARCHAR NOT NULL,
            firstname VARCHAR NOT NULL,
            sex VARCHAR NOT NULL,
            street_number SMALLINT NOT NULL,
            street_name VARCHAR NOT NULL,
            city VARCHAR NOT NULL,
            postcode VARCHAR NOT NULL,
            region VARCHAR NOT NULL,
            modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
       , parameters: None
[2024-06-06T17:58:31.550+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table, task_id=create_table, execution_date=20240606T175821, start_date=20240606T175830, end_date=20240606T175831
[2024-06-06T17:58:31.635+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-06T17:58:31.710+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
