[2024-05-28T18:42:09.216+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:41:40+00:00 [queued]>
[2024-05-28T18:42:09.255+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:41:40+00:00 [queued]>
[2024-05-28T18:42:09.256+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T18:42:09.298+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task4> on 2024-05-28 18:41:40+00:00
[2024-05-28T18:42:09.318+0000] {standard_task_runner.py:60} INFO - Started process 3831 to run task
[2024-05-28T18:42:09.330+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork2_dag', 'task4', 'scheduled__2024-05-28T18:41:40+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/fork_2.py', '--cfg-path', '/tmp/tmpjqq7w9ln']
[2024-05-28T18:42:09.335+0000] {standard_task_runner.py:88} INFO - Job 208: Subtask task4
[2024-05-28T18:42:09.379+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T18:42:09.444+0000] {task_command.py:423} INFO - Running <TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:41:40+00:00 [running]> on host ac6c883b25f7
[2024-05-28T18:42:09.593+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork2_dag' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T18:41:40+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T18:41:40+00:00'
[2024-05-28T18:42:09.596+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T18:42:09.597+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T18:42:09.611+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork2_dag, task_id=task4, execution_date=20240528T184140, start_date=20240528T184209, end_date=20240528T184209
[2024-05-28T18:42:09.669+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T18:42:09.734+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
