[2024-05-28T19:11:33.253+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:10+00:00 [queued]>
[2024-05-28T19:11:33.335+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:10+00:00 [queued]>
[2024-05-28T19:11:33.339+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T19:11:33.539+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task1> on 2024-05-28 19:11:10+00:00
[2024-05-28T19:11:33.655+0000] {standard_task_runner.py:60} INFO - Started process 4902 to run task
[2024-05-28T19:11:33.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork3_dag', 'task1', 'scheduled__2024-05-28T19:11:10+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/fork_3.py', '--cfg-path', '/tmp/tmpuu3oxqcb']
[2024-05-28T19:11:33.702+0000] {standard_task_runner.py:88} INFO - Job 250: Subtask task1
[2024-05-28T19:11:33.893+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:11:34.517+0000] {task_command.py:423} INFO - Running <TaskInstance: fork3_dag.task1 scheduled__2024-05-28T19:11:10+00:00 [running]> on host ac6c883b25f7
[2024-05-28T19:11:35.113+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork3_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T19:11:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T19:11:10+00:00'
[2024-05-28T19:11:35.115+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T19:11:35.116+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T19:11:35.144+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork3_dag, task_id=task1, execution_date=20240528T191110, start_date=20240528T191133, end_date=20240528T191135
[2024-05-28T19:11:35.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T19:11:35.571+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
