[2024-05-28T18:43:29.295+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:43:00+00:00 [queued]>
[2024-05-28T18:43:29.342+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:43:00+00:00 [queued]>
[2024-05-28T18:43:29.344+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T18:43:29.392+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task4> on 2024-05-28 18:43:00+00:00
[2024-05-28T18:43:29.415+0000] {standard_task_runner.py:60} INFO - Started process 3933 to run task
[2024-05-28T18:43:29.425+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fork2_dag', 'task4', 'scheduled__2024-05-28T18:43:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/fork_2.py', '--cfg-path', '/tmp/tmpie7vc13w']
[2024-05-28T18:43:29.439+0000] {standard_task_runner.py:88} INFO - Job 232: Subtask task4
[2024-05-28T18:43:29.470+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T18:43:29.624+0000] {task_command.py:423} INFO - Running <TaskInstance: fork2_dag.task4 scheduled__2024-05-28T18:43:00+00:00 [running]> on host ac6c883b25f7
[2024-05-28T18:43:29.919+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fork2_dag' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T18:43:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T18:43:00+00:00'
[2024-05-28T18:43:29.921+0000] {logging_mixin.py:188} INFO - success
[2024-05-28T18:43:29.922+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T18:43:29.944+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fork2_dag, task_id=task4, execution_date=20240528T184300, start_date=20240528T184329, end_date=20240528T184329
[2024-05-28T18:43:30.023+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T18:43:30.085+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
